spring:
  application:
    name: PopoAlbum
  datasource:
    url: jdbc:postgresql://localhost:5432/popoalbum
    username: postgres
    password: saypg0509
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB