spring:
  application:
    name: PopoAlbum
  datasource:
    url: jdbc:postgresql://localhost:5432/popoalbum
    username: postgres
    password: saypg0509
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
