spring:
  application:
    name: SnapShelf
  
  datasource:
    url: jdbc:postgresql://localhost:5432/snapshelf
    username: postgres
    password: saypg0509
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: ${PORT:8080}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  config:
    additional-location: classpath:/keys/vision-key.json



google:
  cloud:
    credentials:
      location: classpath:/keys/vision-key.json